/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WhitepaperRouteImport } from './routes/whitepaper'
import { Route as TreasuryRouteImport } from './routes/treasury'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SwapRouteImport } from './routes/swap'
import { Route as StakingRouteImport } from './routes/staking'
import { Route as SecurityRouteImport } from './routes/security'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as NftLaunchpadRouteImport } from './routes/nft-launchpad'
import { Route as MerchRouteImport } from './routes/merch'
import { Route as LegacyVaultRouteImport } from './routes/legacy-vault'
import { Route as KidsRouteImport } from './routes/kids'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as EcosystemRouteImport } from './routes/ecosystem'
import { Route as DreamweaverRouteImport } from './routes/dreamweaver'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const WhitepaperRoute = WhitepaperRouteImport.update({
  id: '/whitepaper',
  path: '/whitepaper',
  getParentRoute: () => rootRouteImport,
} as any)
const TreasuryRoute = TreasuryRouteImport.update({
  id: '/treasury',
  path: '/treasury',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SwapRoute = SwapRouteImport.update({
  id: '/swap',
  path: '/swap',
  getParentRoute: () => rootRouteImport,
} as any)
const StakingRoute = StakingRouteImport.update({
  id: '/staking',
  path: '/staking',
  getParentRoute: () => rootRouteImport,
} as any)
const SecurityRoute = SecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const NftLaunchpadRoute = NftLaunchpadRouteImport.update({
  id: '/nft-launchpad',
  path: '/nft-launchpad',
  getParentRoute: () => rootRouteImport,
} as any)
const MerchRoute = MerchRouteImport.update({
  id: '/merch',
  path: '/merch',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyVaultRoute = LegacyVaultRouteImport.update({
  id: '/legacy-vault',
  path: '/legacy-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const KidsRoute = KidsRouteImport.update({
  id: '/kids',
  path: '/kids',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const EcosystemRoute = EcosystemRouteImport.update({
  id: '/ecosystem',
  path: '/ecosystem',
  getParentRoute: () => rootRouteImport,
} as any)
const DreamweaverRoute = DreamweaverRouteImport.update({
  id: '/dreamweaver',
  path: '/dreamweaver',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dreamweaver': typeof DreamweaverRoute
  '/ecosystem': typeof EcosystemRoute
  '/faq': typeof FaqRoute
  '/kids': typeof KidsRoute
  '/legacy-vault': typeof LegacyVaultRoute
  '/merch': typeof MerchRoute
  '/nft-launchpad': typeof NftLaunchpadRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/treasury': typeof TreasuryRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dreamweaver': typeof DreamweaverRoute
  '/ecosystem': typeof EcosystemRoute
  '/faq': typeof FaqRoute
  '/kids': typeof KidsRoute
  '/legacy-vault': typeof LegacyVaultRoute
  '/merch': typeof MerchRoute
  '/nft-launchpad': typeof NftLaunchpadRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/treasury': typeof TreasuryRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/dreamweaver': typeof DreamweaverRoute
  '/ecosystem': typeof EcosystemRoute
  '/faq': typeof FaqRoute
  '/kids': typeof KidsRoute
  '/legacy-vault': typeof LegacyVaultRoute
  '/merch': typeof MerchRoute
  '/nft-launchpad': typeof NftLaunchpadRoute
  '/privacy': typeof PrivacyRoute
  '/security': typeof SecurityRoute
  '/staking': typeof StakingRoute
  '/swap': typeof SwapRoute
  '/terms': typeof TermsRoute
  '/treasury': typeof TreasuryRoute
  '/whitepaper': typeof WhitepaperRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/dreamweaver'
    | '/ecosystem'
    | '/faq'
    | '/kids'
    | '/legacy-vault'
    | '/merch'
    | '/nft-launchpad'
    | '/privacy'
    | '/security'
    | '/staking'
    | '/swap'
    | '/terms'
    | '/treasury'
    | '/whitepaper'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/dreamweaver'
    | '/ecosystem'
    | '/faq'
    | '/kids'
    | '/legacy-vault'
    | '/merch'
    | '/nft-launchpad'
    | '/privacy'
    | '/security'
    | '/staking'
    | '/swap'
    | '/terms'
    | '/treasury'
    | '/whitepaper'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/dreamweaver'
    | '/ecosystem'
    | '/faq'
    | '/kids'
    | '/legacy-vault'
    | '/merch'
    | '/nft-launchpad'
    | '/privacy'
    | '/security'
    | '/staking'
    | '/swap'
    | '/terms'
    | '/treasury'
    | '/whitepaper'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  DreamweaverRoute: typeof DreamweaverRoute
  EcosystemRoute: typeof EcosystemRoute
  FaqRoute: typeof FaqRoute
  KidsRoute: typeof KidsRoute
  LegacyVaultRoute: typeof LegacyVaultRoute
  MerchRoute: typeof MerchRoute
  NftLaunchpadRoute: typeof NftLaunchpadRoute
  PrivacyRoute: typeof PrivacyRoute
  SecurityRoute: typeof SecurityRoute
  StakingRoute: typeof StakingRoute
  SwapRoute: typeof SwapRoute
  TermsRoute: typeof TermsRoute
  TreasuryRoute: typeof TreasuryRoute
  WhitepaperRoute: typeof WhitepaperRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/whitepaper': {
      id: '/whitepaper'
      path: '/whitepaper'
      fullPath: '/whitepaper'
      preLoaderRoute: typeof WhitepaperRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treasury': {
      id: '/treasury'
      path: '/treasury'
      fullPath: '/treasury'
      preLoaderRoute: typeof TreasuryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/swap': {
      id: '/swap'
      path: '/swap'
      fullPath: '/swap'
      preLoaderRoute: typeof SwapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/staking': {
      id: '/staking'
      path: '/staking'
      fullPath: '/staking'
      preLoaderRoute: typeof StakingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/security': {
      id: '/security'
      path: '/security'
      fullPath: '/security'
      preLoaderRoute: typeof SecurityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft-launchpad': {
      id: '/nft-launchpad'
      path: '/nft-launchpad'
      fullPath: '/nft-launchpad'
      preLoaderRoute: typeof NftLaunchpadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/merch': {
      id: '/merch'
      path: '/merch'
      fullPath: '/merch'
      preLoaderRoute: typeof MerchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy-vault': {
      id: '/legacy-vault'
      path: '/legacy-vault'
      fullPath: '/legacy-vault'
      preLoaderRoute: typeof LegacyVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kids': {
      id: '/kids'
      path: '/kids'
      fullPath: '/kids'
      preLoaderRoute: typeof KidsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecosystem': {
      id: '/ecosystem'
      path: '/ecosystem'
      fullPath: '/ecosystem'
      preLoaderRoute: typeof EcosystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dreamweaver': {
      id: '/dreamweaver'
      path: '/dreamweaver'
      fullPath: '/dreamweaver'
      preLoaderRoute: typeof DreamweaverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  DreamweaverRoute: DreamweaverRoute,
  EcosystemRoute: EcosystemRoute,
  FaqRoute: FaqRoute,
  KidsRoute: KidsRoute,
  LegacyVaultRoute: LegacyVaultRoute,
  MerchRoute: MerchRoute,
  NftLaunchpadRoute: NftLaunchpadRoute,
  PrivacyRoute: PrivacyRoute,
  SecurityRoute: SecurityRoute,
  StakingRoute: StakingRoute,
  SwapRoute: SwapRoute,
  TermsRoute: TermsRoute,
  TreasuryRoute: TreasuryRoute,
  WhitepaperRoute: WhitepaperRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
